# En este archivo define un servicio de Kubernetes para la aplicación backend. Es el load balancer que expone el backend al exterior.
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
