# Servicio para exponer el frontend de la aplicación a través de un LoadBalancer en Kubernetes.
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
